openai:
  api_key: *********
  engine: gpt-3.5-turbo-instruct

database:
  host: localhost
  port: 5432
  user: *****
  password: *****
  database: *****

environment:
  env: local # Possible [ local, prod ]
